/**
 * Shared per-request loader for competition-image renderers.
 *
 * Fetches a Payload page by slug, resolves the hero theme into concrete colors,
 * surfaces the CompetitionHero + CompetitionNav data, and provides an
 * image-as-data-URI helper so Satori (which can't fetch its own assets) can
 * embed photos inline.
 *
 * Used by both `/api/og` (1200×630) and `/api/competition-image/login-*`
 * templates. Each template still owns its own JSX layout — this file just
 * normalizes the inputs.
 */
import { basename } from 'path'
import { getPayload } from 'payload'
import configPromise from '@payload-config'
import { DEFAULT_HERO_THEME } from '@/puck/theme'
import type { PuckData } from '@/puck/types'

/** Resolve theme token to actual hex color. Satori has no CSS-var context. */
function resolveColor(token: string, primaryDark: string, primaryBright: string): string {
  if (token === 'dark') return primaryDark
  if (token === 'bright') return primaryBright
  return '#ffffff'
}

export interface ResolvedColors {
  primaryDark: string
  primaryBright: string
  overlayColor: string
  highlightBg: string
  highlightText: string
  heroText: string
}

function resolveTheme(rootProps: PuckData['root']['props'] | undefined): ResolvedColors {
  const primaryDark = rootProps?.primaryDark || '#222'
  const primaryBright = rootProps?.primaryBright || primaryDark

  const theme = rootProps?.heroTheme || DEFAULT_HERO_THEME
  const [overlayToken, highlightBgToken, highlightTextToken] = theme.split('-')
  const overlayColor = resolveColor(overlayToken, primaryDark, primaryBright)
  const highlightBg = resolveColor(highlightBgToken, primaryDark, primaryBright)
  const highlightText = resolveColor(highlightTextToken, primaryDark, primaryBright)

  const oppositeOverlay = overlayToken === 'dark' ? 'bright' : 'dark'
  const heroTextStyle = rootProps?.heroTextStyle || 'default'
  const heroText =
    heroTextStyle === 'white'
      ? '#ffffff'
      : heroTextStyle === 'primary'
        ? resolveColor(oppositeOverlay, primaryDark, primaryBright)
        : highlightBg

  return { primaryDark, primaryBright, overlayColor, highlightBg, highlightText, heroText }
}

/**
 * Sizes generated by `Media.ts` `imageSizes`. Templates pick which one to
 * fetch via `fetchAsDataUri(..., sizeKey)`. Keeping this as a union (vs `string`)
 * lets `doc.sizes[sizeKey]` typecheck against Payload's generated Media type
 * without a cast.
 */
export type MediaSizeKey = 'thumbnail' | 'square' | 'small' | 'medium' | 'large' | 'xlarge' | 'og'

export interface CompetitionImageData {
  rootProps: PuckData['root']['props'] | undefined
  hero: ReturnType<typeof findHero>
  partnerLogo: ReturnType<typeof findPartnerLogo>
  colors: ResolvedColors
  /** Resolves a media URL to a data URI Satori can embed. */
  fetchAsDataUri: (
    url: string | undefined,
    label: string,
    sizeKey?: MediaSizeKey,
  ) => Promise<string>
}

async function loadPage(slug: string) {
  const payload = await getPayload({ config: configPromise })
  const result = await payload.find({
    collection: 'pages',
    limit: 1,
    pagination: false,
    where: { slug: { equals: slug } },
  })
  return { page: result.docs?.[0], payload }
}

function findHero(content: PuckData['content'] | undefined) {
  return content?.find((c) => c.type === 'CompetitionHero')?.props
}

function findPartnerLogo(content: PuckData['content'] | undefined) {
  const nav = content?.find((c) => c.type === 'CompetitionNav')?.props
  return nav?.partnerLogo ?? null
}

/**
 * Build a fetcher that:
 *   1. Looks up the Payload media doc by filename so we can pick a sized variant.
 *   2. Fetches the resolved URL with `Accept: image/png,image/jpeg` — Satori
 *      can't decode webp, and CF Polish optimizes losslessly (~33% smaller).
 *   3. Returns a `data:` URI for inline embedding in Satori JSX.
 *
 * `sizeKey` selects which Media variant (e.g. 'og', 'xlarge'). Falls back to
 * the original when the variant is missing.
 */
function createImageFetcher(payload: Awaited<ReturnType<typeof getPayload>>) {
  const resolveSizedUrl = async (
    url: string | undefined,
    sizeKey: MediaSizeKey,
  ): Promise<string> => {
    if (!url) return ''
    const filename = basename(new URL(url).pathname)
    const media = await payload.find({
      collection: 'media',
      where: { filename: { equals: filename } },
      limit: 1,
      // sizes: variant URLs. url: fallback. prefix: required by S3 plugin's
      // afterRead hook to regenerate URLs with correct folder path.
      select: { sizes: true, url: true, prefix: true },
    })
    return media.docs?.[0]?.sizes?.[sizeKey]?.url || url
  }

  return async (
    url: string | undefined,
    label: string,
    sizeKey: MediaSizeKey = 'og',
  ): Promise<string> => {
    if (!url) return ''
    const resolved = await resolveSizedUrl(url, sizeKey)
    try {
      const res = await fetch(resolved, {
        headers: { Accept: 'image/png,image/jpeg,image/*' },
      })
      if (!res.ok) {
        console.warn(`[competition-image] ${label}: fetch ${res.status} for ${resolved}`)
        return ''
      }
      const contentType = res.headers.get('content-type') || 'image/png'
      const buf = await res.arrayBuffer()
      return `data:${contentType};base64,${Buffer.from(buf).toString('base64')}`
    } catch (e) {
      console.error(`[competition-image] ${label}:`, e)
      return ''
    }
  }
}

/**
 * Top-level loader. Returns null if the page doesn't exist — caller renders
 * a fallback. Otherwise returns the typed content + fetchers each template
 * needs to assemble its layout.
 */
export async function loadCompetitionImageData(slug: string): Promise<CompetitionImageData | null> {
  const { page, payload } = await loadPage(slug)
  if (!page) return null

  // One cast at the Payload DB boundary — payload's JSON column is typed `any`.
  // Downstream access is fully typed via PuckData = Data<Components, RootProps>.
  const puckData = page.puckData as PuckData | undefined
  const rootProps = puckData?.root?.props
  const content = puckData?.content

  return {
    rootProps,
    hero: findHero(content),
    partnerLogo: findPartnerLogo(content),
    colors: resolveTheme(rootProps),
    fetchAsDataUri: createImageFetcher(payload),
  }
}
